// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zkH1ICptIkMnnKXuRDDvSvoIk8FCTpM',
    appId: '1:95130209390:web:e4bc015c38e97d57fdaa7f',
    messagingSenderId: '95130209390',
    projectId: 'flutter-e-manav',
    authDomain: 'flutter-e-manav.firebaseapp.com',
    storageBucket: 'flutter-e-manav.appspot.com',
    measurementId: 'G-XPCYMWE4HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4hib2cvAd8JloEbidNJvTvVBnkj1M7AM',
    appId: '1:95130209390:android:adf5c209d7fc8461fdaa7f',
    messagingSenderId: '95130209390',
    projectId: 'flutter-e-manav',
    storageBucket: 'flutter-e-manav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURE2if-NQ4OwBEKbuJ530JPHVEJoN3XA',
    appId: '1:95130209390:ios:cb72d5ce4c79ac6efdaa7f',
    messagingSenderId: '95130209390',
    projectId: 'flutter-e-manav',
    storageBucket: 'flutter-e-manav.appspot.com',
    iosClientId: '95130209390-5gg2th4eqgslgpvslbrie2dp9c4av2ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEManav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURE2if-NQ4OwBEKbuJ530JPHVEJoN3XA',
    appId: '1:95130209390:ios:cb72d5ce4c79ac6efdaa7f',
    messagingSenderId: '95130209390',
    projectId: 'flutter-e-manav',
    storageBucket: 'flutter-e-manav.appspot.com',
    iosClientId: '95130209390-5gg2th4eqgslgpvslbrie2dp9c4av2ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEManav',
  );
}
